// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AniCard: typeof import('./src/components/anime-card/AniCard.vue')['default']
    ArrowDown: typeof import('./src/icons/ArrowDown.vue')['default']
    Container: typeof import('./src/layout/Container.vue')['default']
    FilterBar: typeof import('./src/components/filter/FilterBar.vue')['default']
    FilterIcon: typeof import('./src/icons/FilterIcon.vue')['default']
    Footer: typeof import('./src/layout/Footer.vue')['default']
    FormInput: typeof import('./src/components/form/input/FormInput.vue')['default']
    FormSelect: typeof import('./src/components/form/input/FormSelect.vue')['default']
    Hero: typeof import('./src/views/home/components/hero/Hero.vue')['default']
    LandingHeading: typeof import('./src/views/home/components/landing/LandingHeading.vue')['default']
    LandingSection: typeof import('./src/views/home/components/landing/LandingSection.vue')['default']
    Navigation: typeof import('./src/components/nav/Navigation.vue')['default']
    NeutraIcon: typeof import('./src/icons/NeutraIcon.vue')['default']
    Neutralcon: typeof import('./src/icons/NeutraIcon.vue')['default']
    Ranking: typeof import('./src/views/home/components/ranking/Ranking.vue')['default']
    RankingItem: typeof import('./src/views/home/components/ranking/RankingItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SadIcon: typeof import('./src/icons/SadIcon.vue')['default']
    SearchIcon: typeof import('./src/icons/SearchIcon.vue')['default']
    Skeleton: typeof import('./src/components/skeleton/Skeleton.vue')['default']
    Slider: typeof import('./src/components/slider/Slider.vue')['default']
    SmileIcon: typeof import('./src/icons/SmileIcon.vue')['default']
    TagIcon: typeof import('./src/icons/TagIcon.vue')['default']
    Undefined: typeof import('./src/views/home/index.vue')['default']
    UseElementInView: typeof import('./src/composables/useElementInView.vue')['default']
    UseEventListener: typeof import('./src/composables/useEventListener.vue')['default']
    UseInViewport: typeof import('./src/composables/useInViewport.vue')['default']
  }
}
