// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Container: typeof import('./src/layout/Container.vue')['default']
    Hero: typeof import('./src/components/hero/Hero.vue')['default']
    Navigation: typeof import('./src/components/nav/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/hero/test.vue')['default']
    Undefined: typeof import('./src/views/home/index.vue')['default']
  }
}
