// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AniCard: typeof import('./src/components/anime-card/AniCard.vue')['default']
    AnimeList: typeof import('./src/components/feature/home/AnimeList/AnimeList.vue')['default']
    AnimeListHome: typeof import('./src/components/feature/home/AnimeList/AnimeListHome.vue')['default']
    ArrowDown: typeof import('./src/icons/ArrowDown.vue')['default']
    CloseIcon: typeof import('./src/icons/CloseIcon.vue')['default']
    Container: typeof import('./src/layout/Container.vue')['default']
    FilterBar: typeof import('./src/components/filter/FilterBar.vue')['default']
    FilterIcon: typeof import('./src/icons/FilterIcon.vue')['default']
    Footer: typeof import('./src/layout/Footer.vue')['default']
    FormInput: typeof import('./src/components/form/FormInput.vue')['default']
    FormRange: typeof import('./src/components/form/FormRange.vue')['default']
    FormSelect: typeof import('./src/components/form/FormSelect.vue')['default']
    Hero: typeof import('./src/components/feature/home/hero/Hero.vue')['default']
    Home: typeof import('./src/views/home/Home.vue')['default']
    LandingHeading: typeof import('./src/components/feature/home/landing/LandingHeading.vue')['default']
    LandingSection: typeof import('./src/components/feature/home/landing/LandingSection.vue')['default']
    Layout: typeof import('./src/layout/Layout.vue')['default']
    Navigation: typeof import('./src/components/navigation/Navigation.vue')['default']
    NeutraIcon: typeof import('./src/icons/NeutraIcon.vue')['default']
    Ranking: typeof import('./src/components/feature/home/ranking/Ranking.vue')['default']
    RankingItem: typeof import('./src/components/feature/home/ranking/RankingItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SadIcon: typeof import('./src/icons/SadIcon.vue')['default']
    SearchIcon: typeof import('./src/icons/SearchIcon.vue')['default']
    Skeleton: typeof import('./src/components/skeleton/Skeleton.vue')['default']
    SmileIcon: typeof import('./src/icons/SmileIcon.vue')['default']
    TagIcon: typeof import('./src/icons/TagIcon.vue')['default']
  }
}
