name: Check MR is valid & Push image

on: 
   pull_request:
    types: [opened, synchronize, closed]


jobs:
  build:
    runs-on: ubuntu-latest
    if:  (!(github.event.action == 'closed' && github.event.pull_request.merged != true))
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16.19.1'
      - run: npm i -g yarn
      - run: yarn
      - run: yarn build

  push-ecr:
    name: Push docker image 
    runs-on: "ubuntu-latest"
    needs: build
    if: github.event.pull_request.merged == true && github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ani-app
          IMAGE_TAG: ${{ github.sha }}

        run: |
          echo $REGISTRY
          docker build -t $REGISTRY/$REPOSITORY .
          docker tag $REGISTRY/$REPOSITORY $REGISTRY/$REPOSITORY:$IMAGE_TAG && docker tag $REGISTRY/$REPOSITORY $REGISTRY/$REPOSITORY:latest
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          aws ecr batch-delete-image --repository-name $REPOSITORY --image-ids imageTag=latest
          docker push $REGISTRY/$REPOSITORY:latest



    