name: Check MR is valid

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16.19.1'
      - run: npm i -g yarn
      - run: yarn
      - run: yarn build
